apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
  labels:
    app: python-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-flask-app
  template:
    metadata:
      labels:
        app: python-flask-app
    spec:
      containers:
      - name: python-flask-app
        image: ${DOCKER_IMAGE}/${IMAGE_TAG}
        imagePullPolicy: IfNotPresent  # Use local image if available
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: python-flask-app-service
spec:
  type: NodePort
  selector:
    app: python-flask-app
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000